export async function GET() {
  return Response.json({
    USE_MOCK_DATA: process.env.USE_MOCK_DATA,
    TBO_USERNAME: process.env.TBO_USERNAME,
    TBO_HOTEL_BASE_URL: process.env.TBO_HOTEL_BASE_URL,
    TBO_HOTEL_COUNTRY_CODE: process.env.TBO_HOTEL_COUNTRY_CODE,
    TBO_HOTEL_CATALOG_ONLY: process.env.TBO_HOTEL_CATALOG_ONLY,
    TBO_HOTEL_CATALOG_RESULT_LIMIT: process.env.TBO_HOTEL_CATALOG_RESULT_LIMIT,
    TBO_HOTEL_CODE_LIMIT: process.env.TBO_HOTEL_CODE_LIMIT,
    TBO_HOTEL_FLEX_SEARCH: process.env.TBO_HOTEL_FLEX_SEARCH,
    TBO_HOTEL_FLEX_DAY_OFFSETS: process.env.TBO_HOTEL_FLEX_DAY_OFFSETS,
    TBO_HOTEL_SEARCH_TIMEOUT_MS: process.env.TBO_HOTEL_SEARCH_TIMEOUT_MS,
    TBO_AIR_AUTH_URL: process.env.TBO_AIR_AUTH_URL,
    TBO_AIR_SEARCH_URL: process.env.TBO_AIR_SEARCH_URL,
    TBO_DEMO_HOTEL_CODES: process.env.TBO_DEMO_HOTEL_CODES,
  });
}
